Update serializers.py
 from django.utils.translation import ugettext as _
ImportError: cannot import name 'ugettext' from 'django.utils.translation'

It was removed from Django 4, use this option: from django.utils.translation import gettext as _